// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_type::Message;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

impl __core::Table for Message {
    type Module = RemoteModule;
    type Row = Message;
    type Pk = __core::NoPk;
    const NAME: &'static str = "message";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(_: &Message) -> Option<&__core::NoPk> {
        None
    }
}
