// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug, __reflect::Reflect)]
#[sats(crate = __lib)]
pub struct Message {
    #[reflect(remote = __sats_reflect::IdentityRemote)]
    pub sender: __lib::Identity,
    #[reflect(remote = __sats_reflect::TimestampRemote)]
    pub sent: __lib::Timestamp,
    pub text: String,
}

/// The columns of `Message`, for typed queries.
pub struct MessageCols {
    pub sender: __query::Col<Message, __lib::Identity>,
    pub sent: __query::Col<Message, __lib::Timestamp>,
    pub text: __query::Col<Message, String>,
}

impl __query::HasCols for Message {
    type Cols = MessageCols;
    fn cols(table: &'static str) -> MessageCols {
        MessageCols {
            sender: __query::Col::new(table, "sender"),
            sent: __query::Col::new(table, "sent"),
            text: __query::Col::new(table, "text"),
        }
    }
}

/// The indexed columns of `Message`, for typed queries.
pub struct MessageIxCols {}

impl __query::HasIxCols for Message {
    type IxCols = MessageIxCols;
    fn ix_cols(table: &'static str) -> MessageIxCols {
        MessageIxCols {}
    }
}

impl __query::CanBeLookupTable for Message {}
