// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.11.0 (commit 91b5f3eb204c7632292db1f57e452f99dd1c054e).

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

pub mod message_table;
pub mod message_type;
pub mod send_message_reducer;
pub mod set_name_reducer;
pub mod user_table;
pub mod user_type;

pub use message_table::*;
pub use message_type::Message;
pub use send_message_reducer::SendMessage;
pub use set_name_reducer::SetName;
pub use user_table::*;
pub use user_type::User;

/// The module these bindings were generated from.
#[derive(Debug)]
pub struct RemoteModule;

/// One method per reducer on [`spacetimedb_bevy::Reducers`].
pub trait RemoteReducers {
    fn send_message(&self, text: String) -> spacetimedb_bevy::RequestId;
    fn set_name(&self, name: String) -> spacetimedb_bevy::RequestId;
}

impl RemoteReducers for spacetimedb_bevy::Reducers<'_, RemoteModule> {
    fn send_message(&self, text: String) -> spacetimedb_bevy::RequestId {
        self.call(SendMessage { text })
    }
    fn set_name(&self, name: String) -> spacetimedb_bevy::RequestId {
        self.call(SetName { name })
    }
}

/// Where typed queries start: `query::user().filter(|user| user.online.eq(true))`.
/// Pass one to `commands.subscribe_to::<RemoteModule, _>(..)`.
pub mod query {
    use super::__query;

    /// Every row of `message`, to narrow with `filter` or join.
    pub fn message() -> __query::Table<super::Message> {
        __query::Table::new("message")
    }
    /// Every row of `user`, to narrow with `filter` or join.
    pub fn user() -> __query::Table<super::User> {
        __query::Table::new("user")
    }
}

/// The changes one server message makes, per table.
#[derive(Default, Debug)]
pub struct RemoteUpdate {
    pub message: __core::TableUpdate<Message>,
    pub user: __core::TableUpdate<User>,
}

impl __core::Module for RemoteModule {
    type Update = RemoteUpdate;

    fn parse_table(
        update: &mut RemoteUpdate,
        table: &str,
        rows: __core::RawTableRows,
    ) -> Result<(), __core::ParseError> {
        match table {
            "message" => update.message.append("message", rows),
            "user" => update.user.append("user", rows),
            unknown => Err(__core::ParseError::UnknownTable(unknown.into())),
        }
    }

    fn visit_update<V: __core::UpdateVisitor<Self>>(update: RemoteUpdate, visitor: &mut V) {
        visitor.table::<Message>(update.message);
        visitor.table::<User>(update.user);
    }

    fn visit_tables<V: __core::TableVisitor<Self>>(visitor: &mut V) {
        visitor.table::<Message>();
        visitor.table::<User>();
    }

    fn visit_reducers<V: __core::ReducerVisitor<Self>>(visitor: &mut V) {
        visitor.reducer::<SendMessage>();
        visitor.reducer::<SetName>();
    }
}

impl __sats_reflect::ReflectTables for RemoteModule {
    fn visit_reflect_tables<V: __sats_reflect::ReflectTableVisitor<Self>>(visitor: &mut V) {
        visitor.table::<Message>();
        visitor.table::<User>();
    }
}
