// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_type::User;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

impl __core::Table for User {
    type Module = RemoteModule;
    type Row = User;
    type Pk = __lib::Identity;
    const NAME: &'static str = "user";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(row: &User) -> Option<&__lib::Identity> {
        Some(&row.identity)
    }
    fn pk_from_bsatn(mut bsatn: &[u8]) -> Result<Option<__lib::Identity>, __lib::bsatn::DecodeError> {
        __lib::bsatn::from_reader(&mut bsatn).map(Some)
    }
}
