// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug, __reflect::Reflect)]
#[sats(crate = __lib)]
pub struct User {
    #[reflect(remote = __sats_reflect::IdentityRemote)]
    pub identity: __lib::Identity,
    pub name: Option<String>,
    pub online: bool,
}

/// The columns of `User`, for typed queries.
pub struct UserCols {
    pub identity: __query::Col<User, __lib::Identity>,
    pub name: __query::Col<User, Option<String>>,
    pub online: __query::Col<User, bool>,
}

impl __query::HasCols for User {
    type Cols = UserCols;
    fn cols(table: &'static str) -> UserCols {
        UserCols {
            identity: __query::Col::new(table, "identity"),
            name: __query::Col::new(table, "name"),
            online: __query::Col::new(table, "online"),
        }
    }
}

/// The indexed columns of `User`, for typed queries.
pub struct UserIxCols {
    pub identity: __query::IxCol<User, __lib::Identity>,
}

impl __query::HasIxCols for User {
    type IxCols = UserIxCols;
    fn ix_cols(table: &'static str) -> UserIxCols {
        UserIxCols {
            identity: __query::IxCol::new(table, "identity"),
        }
    }
}

impl __query::CanBeLookupTable for User {}
