// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.11.0 (commit 91b5f3eb204c7632292db1f57e452f99dd1c054e).

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

pub mod delete_player_reducer;
pub mod insert_player_reducer;
pub mod move_player_reducer;
pub mod my_player_and_level_table;
pub mod my_player_table;
pub mod nearby_players_table;
pub mod player_and_level_type;
pub mod player_level_table;
pub mod player_level_type;
pub mod player_location_type;
pub mod player_table;
pub mod player_type;
pub mod players_at_level_0_table;

pub use delete_player_reducer::DeletePlayer;
pub use insert_player_reducer::InsertPlayer;
pub use move_player_reducer::MovePlayer;
pub use my_player_and_level_table::*;
pub use my_player_table::*;
pub use nearby_players_table::*;
pub use player_and_level_type::PlayerAndLevel;
pub use player_level_table::*;
pub use player_level_type::PlayerLevel;
pub use player_location_type::PlayerLocation;
pub use player_table::*;
pub use player_type::Player;
pub use players_at_level_0_table::*;

/// The module these bindings were generated from.
#[derive(Debug)]
pub struct RemoteModule;

/// One method per reducer on [`spacetimedb_bevy::Reducers`].
pub trait RemoteReducers {
    fn delete_player(&self, identity: __lib::Identity) -> spacetimedb_bevy::RequestId;
    fn insert_player(&self, identity: __lib::Identity, level: u64) -> spacetimedb_bevy::RequestId;
    fn move_player(&self, dx: i32, dy: i32) -> spacetimedb_bevy::RequestId;
}

impl RemoteReducers for spacetimedb_bevy::Reducers<'_, RemoteModule> {
    fn delete_player(&self, identity: __lib::Identity) -> spacetimedb_bevy::RequestId {
        self.call(DeletePlayer { identity })
    }
    fn insert_player(&self, identity: __lib::Identity, level: u64) -> spacetimedb_bevy::RequestId {
        self.call(InsertPlayer { identity, level })
    }
    fn move_player(&self, dx: i32, dy: i32) -> spacetimedb_bevy::RequestId {
        self.call(MovePlayer { dx, dy })
    }
}

/// Where typed queries start: `query::user().filter(|user| user.online.eq(true))`.
/// Pass one to `commands.subscribe_to::<RemoteModule, _>(..)`.
pub mod query {
    use super::__query;

    /// Every row of `my_player`, to narrow with `filter` or join.
    pub fn my_player() -> __query::Table<super::Player> {
        __query::Table::new("my_player")
    }
    /// Every row of `my_player_and_level`, to narrow with `filter` or join.
    pub fn my_player_and_level() -> __query::Table<super::PlayerAndLevel> {
        __query::Table::new("my_player_and_level")
    }
    /// Every row of `nearby_players`, to narrow with `filter` or join.
    pub fn nearby_players() -> __query::Table<super::PlayerLocation> {
        __query::Table::new("nearby_players")
    }
    /// Every row of `player`, to narrow with `filter` or join.
    pub fn player() -> __query::Table<super::Player> {
        __query::Table::new("player")
    }
    /// Every row of `player_level`, to narrow with `filter` or join.
    pub fn player_level() -> __query::Table<super::PlayerLevel> {
        __query::Table::new("player_level")
    }
    /// Every row of `players_at_level_0`, to narrow with `filter` or join.
    pub fn players_at_level_0() -> __query::Table<super::Player> {
        __query::Table::new("players_at_level_0")
    }
}

/// The changes one server message makes, per table.
#[derive(Default, Debug)]
pub struct RemoteUpdate {
    pub my_player: __core::TableUpdate<Player>,
    pub my_player_and_level: __core::TableUpdate<PlayerAndLevel>,
    pub nearby_players: __core::TableUpdate<PlayerLocation>,
    pub player: __core::TableUpdate<Player>,
    pub player_level: __core::TableUpdate<PlayerLevel>,
    pub players_at_level_0: __core::TableUpdate<Player>,
}

impl __core::Module for RemoteModule {
    type Update = RemoteUpdate;

    fn parse_table(
        update: &mut RemoteUpdate,
        table: &str,
        rows: __core::RawTableRows,
    ) -> Result<(), __core::ParseError> {
        match table {
            "my_player" => update.my_player.append("my_player", rows),
            "my_player_and_level" => update.my_player_and_level.append("my_player_and_level", rows),
            "nearby_players" => update.nearby_players.append("nearby_players", rows),
            "player" => update.player.append("player", rows),
            "player_level" => update.player_level.append("player_level", rows),
            "players_at_level_0" => update.players_at_level_0.append("players_at_level_0", rows),
            unknown => Err(__core::ParseError::UnknownTable(unknown.into())),
        }
    }

    fn visit_update<V: __core::UpdateVisitor<Self>>(update: RemoteUpdate, visitor: &mut V) {
        visitor.table::<MyPlayerTable>(update.my_player);
        visitor.table::<PlayerAndLevel>(update.my_player_and_level);
        visitor.table::<NearbyPlayersTable>(update.nearby_players);
        visitor.table::<PlayerTable>(update.player);
        visitor.table::<PlayerLevel>(update.player_level);
        visitor.table::<PlayersAtLevel0Table>(update.players_at_level_0);
    }

    fn visit_tables<V: __core::TableVisitor<Self>>(visitor: &mut V) {
        visitor.table::<MyPlayerTable>();
        visitor.table::<PlayerAndLevel>();
        visitor.table::<NearbyPlayersTable>();
        visitor.table::<PlayerTable>();
        visitor.table::<PlayerLevel>();
        visitor.table::<PlayersAtLevel0Table>();
    }

    fn visit_reducers<V: __core::ReducerVisitor<Self>>(visitor: &mut V) {
        visitor.reducer::<DeletePlayer>();
        visitor.reducer::<InsertPlayer>();
        visitor.reducer::<MovePlayer>();
    }
}

impl __sats_reflect::ReflectTables for RemoteModule {
    fn visit_reflect_tables<V: __sats_reflect::ReflectTableVisitor<Self>>(visitor: &mut V) {
        visitor.table::<MyPlayerTable>();
        visitor.table::<PlayerAndLevel>();
        visitor.table::<NearbyPlayersTable>();
        visitor.table::<PlayerTable>();
        visitor.table::<PlayerLevel>();
        visitor.table::<PlayersAtLevel0Table>();
    }
}
