// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

/// The table `my_player`, which shares its row type with another table.
pub struct MyPlayerTable;

impl __core::Table for MyPlayerTable {
    type Module = RemoteModule;
    type Row = Player;
    type Pk = __core::NoPk;
    const NAME: &'static str = "my_player";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(_: &Player) -> Option<&__core::NoPk> {
        None
    }
}
