// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_and_level_type::PlayerAndLevel;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

impl __core::Table for PlayerAndLevel {
    type Module = RemoteModule;
    type Row = PlayerAndLevel;
    type Pk = __core::NoPk;
    const NAME: &'static str = "my_player_and_level";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(_: &PlayerAndLevel) -> Option<&__core::NoPk> {
        None
    }
}
