// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_location_type::PlayerLocation;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

/// The table `nearby_players`, which shares its row type with another table.
pub struct NearbyPlayersTable;

impl __core::Table for NearbyPlayersTable {
    type Module = RemoteModule;
    type Row = PlayerLocation;
    type Pk = __core::NoPk;
    const NAME: &'static str = "nearby_players";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(_: &PlayerLocation) -> Option<&__core::NoPk> {
        None
    }
}
