// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_level_type::PlayerLevel;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

impl __core::Table for PlayerLevel {
    type Module = RemoteModule;
    type Row = PlayerLevel;
    type Pk = __core::NoPk;
    const NAME: &'static str = "player_level";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(_: &PlayerLevel) -> Option<&__core::NoPk> {
        None
    }
    fn visit_unique_columns<V: __core::UniqueColumnVisitor<Self>>(visitor: &mut V) {
        visitor.column::<PlayerLevelEntityId>();
    }
}

/// The unique column `entity_id` of table `player_level`, for `Rows::find`.
pub struct PlayerLevelEntityId;

impl __core::UniqueColumn for PlayerLevelEntityId {
    type Table = PlayerLevel;
    type Key = u64;
    const NAME: &'static str = "entity_id";
    fn key(row: &PlayerLevel) -> &u64 {
        &row.entity_id
    }
}
