// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use super::RemoteModule;
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

/// The table `player`, which shares its row type with another table.
pub struct PlayerTable;

impl __core::Table for PlayerTable {
    type Module = RemoteModule;
    type Row = Player;
    type Pk = u64;
    const NAME: &'static str = "player";
    const KIND: __core::TableKind = __core::TableKind::Persistent;
    fn pk(row: &Player) -> Option<&u64> {
        Some(&row.entity_id)
    }
    fn pk_from_bsatn(mut bsatn: &[u8]) -> Result<Option<u64>, __lib::bsatn::DecodeError> {
        __lib::bsatn::from_reader(&mut bsatn).map(Some)
    }
    fn visit_unique_columns<V: __core::UniqueColumnVisitor<Self>>(visitor: &mut V) {
        visitor.column::<PlayerTableIdentity>();
    }
}

/// The unique column `identity` of table `player`, for `Rows::find`.
pub struct PlayerTableIdentity;

impl __core::UniqueColumn for PlayerTableIdentity {
    type Table = PlayerTable;
    type Key = __lib::Identity;
    const NAME: &'static str = "identity";
    fn key(row: &Player) -> &__lib::Identity {
        &row.identity
    }
}
