// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug, __reflect::Reflect)]
#[sats(crate = __lib)]
pub struct PlayerAndLevel {
    pub entity_id: u64,
    #[reflect(remote = __sats_reflect::IdentityRemote)]
    pub identity: __lib::Identity,
    pub level: u64,
}

/// The columns of `PlayerAndLevel`, for typed queries.
pub struct PlayerAndLevelCols {
    pub entity_id: __query::Col<PlayerAndLevel, u64>,
    pub identity: __query::Col<PlayerAndLevel, __lib::Identity>,
    pub level: __query::Col<PlayerAndLevel, u64>,
}

impl __query::HasCols for PlayerAndLevel {
    type Cols = PlayerAndLevelCols;
    fn cols(table: &'static str) -> PlayerAndLevelCols {
        PlayerAndLevelCols {
            entity_id: __query::Col::new(table, "entity_id"),
            identity: __query::Col::new(table, "identity"),
            level: __query::Col::new(table, "level"),
        }
    }
}

/// The indexed columns of `PlayerAndLevel`, for typed queries.
pub struct PlayerAndLevelIxCols {}

impl __query::HasIxCols for PlayerAndLevel {
    type IxCols = PlayerAndLevelIxCols;
    fn ix_cols(table: &'static str) -> PlayerAndLevelIxCols {
        PlayerAndLevelIxCols {}
    }
}

impl __query::CanBeLookupTable for PlayerAndLevel {}
