// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug, __reflect::Reflect)]
#[sats(crate = __lib)]
pub struct PlayerLocation {
    pub entity_id: u64,
    pub active: bool,
    pub x: i32,
    pub y: i32,
}

/// The columns of `PlayerLocation`, for typed queries.
pub struct PlayerLocationCols {
    pub entity_id: __query::Col<PlayerLocation, u64>,
    pub active: __query::Col<PlayerLocation, bool>,
    pub x: __query::Col<PlayerLocation, i32>,
    pub y: __query::Col<PlayerLocation, i32>,
}

impl __query::HasCols for PlayerLocation {
    type Cols = PlayerLocationCols;
    fn cols(table: &'static str) -> PlayerLocationCols {
        PlayerLocationCols {
            entity_id: __query::Col::new(table, "entity_id"),
            active: __query::Col::new(table, "active"),
            x: __query::Col::new(table, "x"),
            y: __query::Col::new(table, "y"),
        }
    }
}

/// The indexed columns of `PlayerLocation`, for typed queries.
pub struct PlayerLocationIxCols {
    pub entity_id: __query::IxCol<PlayerLocation, u64>,
    pub active: __query::IxCol<PlayerLocation, bool>,
}

impl __query::HasIxCols for PlayerLocation {
    type IxCols = PlayerLocationIxCols;
    fn ix_cols(table: &'static str) -> PlayerLocationIxCols {
        PlayerLocationIxCols {
            entity_id: __query::IxCol::new(table, "entity_id"),
            active: __query::IxCol::new(table, "active"),
        }
    }
}

impl __query::CanBeLookupTable for PlayerLocation {}
