// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug, __reflect::Reflect)]
#[sats(crate = __lib)]
pub struct PlayerLevel {
    pub entity_id: u64,
    pub level: u64,
}

/// The columns of `PlayerLevel`, for typed queries.
pub struct PlayerLevelCols {
    pub entity_id: __query::Col<PlayerLevel, u64>,
    pub level: __query::Col<PlayerLevel, u64>,
}

impl __query::HasCols for PlayerLevel {
    type Cols = PlayerLevelCols;
    fn cols(table: &'static str) -> PlayerLevelCols {
        PlayerLevelCols {
            entity_id: __query::Col::new(table, "entity_id"),
            level: __query::Col::new(table, "level"),
        }
    }
}

/// The indexed columns of `PlayerLevel`, for typed queries.
pub struct PlayerLevelIxCols {
    pub entity_id: __query::IxCol<PlayerLevel, u64>,
    pub level: __query::IxCol<PlayerLevel, u64>,
}

impl __query::HasIxCols for PlayerLevel {
    type IxCols = PlayerLevelIxCols;
    fn ix_cols(table: &'static str) -> PlayerLevelIxCols {
        PlayerLevelIxCols {
            entity_id: __query::IxCol::new(table, "entity_id"),
            level: __query::IxCol::new(table, "level"),
        }
    }
}

impl __query::CanBeLookupTable for PlayerLevel {}
