// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_bevy::__codegen::{core as __core, lib as __lib, query as __query, reflect as __reflect};
use spacetimedb_bevy::reflect as __sats_reflect;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug, __reflect::Reflect)]
#[sats(crate = __lib)]
pub struct Player {
    pub entity_id: u64,
    #[reflect(remote = __sats_reflect::IdentityRemote)]
    pub identity: __lib::Identity,
}

/// The columns of `Player`, for typed queries.
pub struct PlayerCols {
    pub entity_id: __query::Col<Player, u64>,
    pub identity: __query::Col<Player, __lib::Identity>,
}

impl __query::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table: &'static str) -> PlayerCols {
        PlayerCols {
            entity_id: __query::Col::new(table, "entity_id"),
            identity: __query::Col::new(table, "identity"),
        }
    }
}

/// The indexed columns of `Player`, for typed queries.
pub struct PlayerIxCols {
    pub entity_id: __query::IxCol<Player, u64>,
    pub identity: __query::IxCol<Player, __lib::Identity>,
}

impl __query::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table: &'static str) -> PlayerIxCols {
        PlayerIxCols {
            entity_id: __query::IxCol::new(table, "entity_id"),
            identity: __query::IxCol::new(table, "identity"),
        }
    }
}

impl __query::CanBeLookupTable for Player {}
